### ISSUE TITLE
Dart 2 runtime failures in tests

### ISSUE THREAD

**Issue by keertip** [dart-lang/shelf#100]
00:02 +4 -1: context null context value becomes empty and immutable [E]                                                                                                                                
  Expected: throws UnsupportedError
    Actual: <Closure: () => String>
     Which: threw ?:<type 'String' is not a subtype of type 'Null' of 'value' where
                    String is from dart:core
                    Null is from dart:core
                  >
            stack dart:collection                                                         MapView.[]=
                  ../../shelf/test/message_test.dart 67:35  main.<fn>.<fn>.<fn>
                  package:test                                                            expect
                  ../..helf/test/message_test.dart 67:7   main.<fn>.<fn>
  
  package:test                                                           expect
  ../..shelf/test/message_test.dart 67:7  main.<fn>.<fn>

00:02 +1 -1: pipes a request from ServerHandler.handler to a mounted handler [E]                                                                                                                       
  type '(Request) => dynamic' is not a subtype of type '(Request) => FutureOr<Response>'
  package:shelf/src/server_handler.dart 30:26                                    ServerHandler.handler
  ../../shelf/test/server_handler_test.dart 23:58  main.<fn>

**Comment by kevmoo** [comment]
Should also clean up the Dart2 constants while we're at it...
