### ISSUE TITLE
Reverse proxy support

### ISSUE THREAD

**Issue by galki** [dart-lang/shelf#122]
Is there a way to implement this? If not, is it possible to get it on the roadmap?

**Comment by kevmoo** [comment]
Shelf is meant to be a very simple API that's easy to extend.

See https://pub.dev/packages?q=shelf

What feature do you want?

**Comment by galki** [comment]
Something like `shelf_proxy` but the reverse. I'd like to serve a local https dev server on `https://example.localhost` and have the requests relayed to `http://localhost:8080`.

**Comment by kevmoo** [comment]
That should be a separate package. Sounds totally doable...
