### ISSUE TITLE
Consider using Map<Symbol, Object> for Request.context 

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/shelf#126]
I know it's a little late in the game, and breaking the API probably a bad idea, but :)

Now that we have extension methods in Dart, it would be very attractive to use private symbols for entries in `Request.context`, and then use an extension method to expose a getter on `shelf.Request`.

I suppose that rather than moving to `Map<Symbol,Object>`, it would be feasible to use `Map<Object,Object>` with would allow private symbols to be used as keys.

**Comment by kevmoo** [comment]
@nex3 and I discussed this many moons ago. The only way to really keep things private is to NOT use a `Map` – anything that exposes the keys will allow folks to reverse engineer this.

I think the benefits of using a `Map` outweigh anything fancy here. You can still do the extension method dance. And `String` is so much easier than `Symbol`

I'll wait to close...if you want to discuss more

**Comment by jonasfj** [comment]
> The only way to really keep things private is to NOT use a Map – anything that exposes the keys will allow folks to reverse engineer this.

Ah, that's a good point...
