### ISSUE TITLE
Add a way to get the remote address of the caller

### ISSUE THREAD

**Issue by Kleak** [dart-lang/shelf#133]
It would be great to have a way to get the address of the user that do a request

**Comment by kevmoo** [comment]
There is a way to do this via the `dart_io` mapping. Ask a question on https://stackoverflow.com/questions/tagged/dart for best results

**Comment by Kleak** [comment]
asked here :
https://stackoverflow.com/questions/61597534/is-there-a-way-with-shelf-to-get-the-address-of-the-caller

**Comment by Kleak** [comment]
ok i have found how to do it

**Comment by sandrobilbeisi** [comment]
There are a couple of official examples for **shelf.io.connection_info** :

https://github.com/dart-lang/shelf/blob/master/lib/shelf_io.dart#L19
https://github.com/dart-lang/shelf/blob/master/test/shelf_io_test.dart#L481

added in Shelf 0.7.1 https://github.com/dart-lang/shelf/blob/519e91d3b7d903e1ee582c4a0306e0342c3c485a/CHANGELOG.md#071
