### ISSUE TITLE
documentation shelf

### ISSUE THREAD

**Issue by MitaiGit** [dart-lang/shelf#136]
What can I do in gRPC? how to work in the shelf + angulardart or flutter_web bundle. The documentation is very sparse, can you make it a little friendlier, perhaps some create blog example?

**Comment by MitaiGit** [comment]
create app "stagehand server-shelf"

**Comment by MitaiGit** [comment]
tell me how to make friends with the shelf c flutter_web? please

**Comment by natebosch** [comment]
A tutorial covering a full backend + frontend setup isn't in scope for this package.

I'd be happy to see someone write one, however this Dart team support for this package isn't targeted for the type of wide usage as the core packages that get more extensive documentation.
