### ISSUE TITLE
`Request.change` broken with latest release

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/shelf#142]
See https://travis-ci.org/github/dart-lang/build/jobs/699942234.

This looks like it was caused by https://github.com/dart-lang/shelf/pull/130.

This is the specific code that is now failing https://github.com/dart-lang/build/blob/554d93df198c53adff9d8d85c043c0ad8ddcdcfe/build_runner/lib/src/server/server.dart#L115.

This is taking an incoming request whose handler path is `"/"` and whose `uri.path` is `"$graph/"`, and then calling `request.change(path: "$graph")` on that.

According to the docs all that is required is that `path` is a prefix of `uri.path` https://pub.dev/documentation/shelf/latest/shelf/Request/change.html.

**Comment by kevmoo** [comment]
CC @jonasfj @natebosch 😟

**Comment by jakemac53** [comment]
The following test (added to `request_test.dart` can repro this issue).
  
```
      test('regression test for Issue #142', () {
        var uri = Uri.parse('https://test.example.com/static/dir/');
        var request = Request('GET', uri,
            handlerPath: '/static/', url: Uri.parse('dir/'));

        var copy = request.change(path: 'dir');
        expect(copy.handlerPath, '/static/dir/');
        expect(copy.url, Uri.parse(''));
      });
```

**Comment by jonasfj** [comment]
Proposed a fix in https://github.com/dart-lang/shelf/pull/143.
