### ISSUE TITLE
Update to support non-nullable

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/shelf#145]
`The symbol 'Cascade' is defined in a legacy library, and can't be re-exported from a non-nullable by default library.
Try removing the export or migrating the legacy library.`

Dart 2.9.0 NNBD, shelf 0.7.7.

**Comment by kevmoo** [comment]
Yup. This package is on our list to migrate to null safety, but it's not at the top of our list.

**Comment by kevmoo** [comment]
This is blocked on migrating `http` and `http_parser` packages.

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/shelf/commit/978cb521881d252dc585601fbb814d696a1d30a5

We should be publishing a preview release shortly
