### ISSUE TITLE
Allow transmitting binary data without special requirements

### ISSUE THREAD

**Issue by kenreilly** [dart-lang/shelf#148]
When I try to send an array of bytes as the body of a Response, I always get this error regardless of how I set encoding or content-type: 

`FormatException: Unexpected extension byte (at offset 0)`

The data is a simple .png image and I've tried passing in a List<int> and a Stream<List<int>>, with different combinations of encoding and content-type, but the result is always the error above. I cannot find a way to send binary data with `shelf` (if there is a way, it should be much, much easier than it is) and for now I'm having to rebuild my server app to handle requests from scratch, since transmitting binary data is a requirement I can't go without.

**Comment by kevmoo** [comment]
Have you tried sending a `List<int>`? Just bytes?

Copy an example of your code here.
