### ISSUE TITLE
Local variable '_echoRequest' can't be referenced before it is declared.

### ISSUE THREAD

**Issue by zhuyonghao** [dart-lang/shelf#151]
![image](https://user-images.githubusercontent.com/18735317/99749317-3d722680-2b19-11eb-8397-886bf6d56d41.png)

**Comment by kevmoo** [comment]
is this within a function?

**Comment by natebosch** [comment]
You have a function local definition of `_echoRequest`. It looks like you copied it from the end of the example into the end of the `main` in the example - 8 lines below the error.
