### ISSUE TITLE
Does the shelf support concurrency?

### ISSUE THREAD

**Issue by hasimyerlikaya** [dart-lang/shelf#157]
I developed a server application using shelf.
The application runs on Google Cloud Run.

Each container in the GCR can simultaneously respond to 80 requests.
Does the shelf support concurrency?
Do I need to update each Container to respond to a request?

Thank you.

![image](https://user-images.githubusercontent.com/7986394/101291124-8d3e3680-3817-11eb-85d2-1404b4c1b22a.png)

**Comment by kevmoo** [comment]
This is a great question!

By default, a Dart program is single threaded – including a trivial shelf server.

But don't worry – Dart's async model support great concurrency. So if you have a server doing other RPCs or doing IO, your server will be able to handle multiple requests at the same time while each request is blocked by file access, network access, etc.

I'm working now on some documentation on a way to use isolates here, too.

For Cloud Run, you default to getting an instance with two cores – it'd be nice to be able to use both, right? 😄

**Comment by hasimyerlikaya** [comment]
Glad to hear that. Shelf seems to be a very good solution.

Two cores are always better than a core 😁
