### ISSUE TITLE
Request.hijack should have a return type of Never

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/shelf#166]
This function always throws, adding a return type of `Never` makes it easier to use this method in functions that return non-nullable values, they otherwise have to put an unreachable throw after calling this method. See https://github.com/dart-lang/shelf_web_socket/pull/31/files/51edc9f50543a5ed463a249d4da71b926779323a#diff-9a79b3ae255d1d23c7c86b78ff48b6f8cc1184d203d9a68a02f0b036751c4e91R88/ as an example.

**Comment by jakemac53** [comment]
I checked on the effect of this change internally, and it does cause a small amount of breakage but it is manageable. The only affected packages are two, third_party packages - package:sse and package:shelf_web_socket.

This is not a breaking change for these packages externally, as it only results in an analyzer info message about dead code.

**Comment by kevmoo** [comment]
Ship it!

**Comment by jakemac53** [comment]
I will circle back to this after getting the null safety releases out the door for shelf_static, shelf_web_socket,  and shelf_packages_handler.
