### ISSUE TITLE
How to I access parameters?

### ISSUE THREAD

**Issue by gat786** [dart-lang/shelf#171]
I am creating a webserver in dart router and trying to gain parameters from url when a request is accepted. 

I know the way of getting parameters which is this [params](https://github.com/google/dart-neats/blob/4f9e2ce596c71925a4de26cce96b3193d949da3e/shelf_router/lib/src/router.dart#L52) but what I am looking for is 

the params which are passed in like this `https://website[dot]com/path?param=value&param2=value` I want to grab hold of param and param2 in the above told example and I didn't find a way of getting those things. Any guidance will be greatly appreciated.

**Comment by kevmoo** [comment]
[Request.url](https://pub.dev/documentation/shelf/latest/shelf/Request/url.html).[queryParameters](https://api.dart.dev/stable/2.12.1/dart-core/Uri/queryParameters.html)

**Comment by gat786** [comment]
Thank you :-)

**Comment by gat786** [comment]
I also want to ask about how can i use templates with dart server. Like is there something like `pug` which can be used to display html templates?
