### ISSUE TITLE
Unable to mount multiple handlers to the same prefix

### ISSUE THREAD

**Issue by olefasting** [dart-lang/shelf#192]
Hello,

Say that I have two services (an authentication service and a profiles service, in my case) and an API service that is meant to bind it all together into a final handler. If I want to prefix the two services with an `/api`' prefix, by mounting both to `/api/` in the API service, only the first handler will be accessible when running the server.

I have tested that everything works, otherwise, by mounting the two services to different prefixes, so the issue seems to lie in the fact that the mounts are both to the same prefix...

This seems like a bug to me, as it is normal practice in libraries like express, which shelf seems to emulate...

Also, when I remap the authentication service to `/` and keep the profiles service at `/api/`, the latter will only work if it is mapped before the former. Very strange behavior, if you ask me....

**Comment by kevmoo** [comment]
Are you using a routing package?

**Comment by olefasting** [comment]
Yes, I am running the shelf_router, so I guess this is the wrong place for this..

Sorry, I'll post this there, in stead, so I guess this can just be closed

**Comment by olefasting** [comment]
I created an issue [here](https://github.com/google/dart-neats/issues/136), in stead, so I'll close this..
