### ISSUE TITLE
Attempting to add values to Request.context errors (the context map is unmodifiable)

### ISSUE THREAD

**Issue by AKushWarrior** [dart-lang/shelf#195]
I was writing a middleware-based library for shelf; based on [this documentation](https://pub.dev/documentation/shelf/latest/shelf/Request/context.html), I believe that middleware/handlers are supposed to edit the Request.context map in order to pass values/state up and down the middleware/handler stack (but please correct me if I'm wrong there!).

When I attempted to edit that Map, I found that it produced a server error, because the Map itself was unmodifiable.

A short snippet for reproduction, similar to the official shelf example but modifying it to demonstrate the issue:
```dart
import 'package:shelf/shelf.dart';
import 'package:shelf/shelf_io.dart';

void main() async {
  var handler = const Pipeline()
      .addMiddleware(logRequests())
      .addHandler(_echoRequest);

  var server = await serve(handler, 'localhost', 8080);

  // Enable content compression
  server.autoCompress = true;

  print('Serving at http://${server.address.host}:${server.port}');
}

Response _echoRequest(Request request) {
  request.context['test'] = 'something';
  return Response.ok('Request for "${request.url}"');
}
```

This snippet will produce an internal server error if you ping it using curl; the logging framework prints us `Unsupported operation: Cannot modify unmodifiable map` (and a stacktrace) on the server-side. The first line of the _echoRequest method is the offending line. 

Note: This particular snippet uses a handler to demonstrate the issue (for simplicity), but middleware suffers from the same issue in my tests (as you might expect, since Request.context always refers to the same object).

I believe the issue is caused by https://github.com/dart-lang/shelf/blob/a16ea0356c3f73fb9e44973b6a52a06c5546fc75/lib/src/message.dart#L99, which assigns context as an unmodifiable map by default. Every other Message constructor carries this behavior; since the Request class delegates context assignment to a super constructor, we have the issue.

**Comment by kevmoo** [comment]
Use [Request.change](https://pub.dev/documentation/shelf/latest/shelf/Request/change.html)

We want these objects to be immutable. `change` returns a new instance with your additions.

**Comment by AKushWarrior** [comment]
Makes sense, thanks.

By the way, for posterity's sake, the issue I was having is that it's pretty difficult to send state with a request using the createMiddleware method. Your comment helped me realize that, if you manually define middleware, you can pipe through a modified request, but that's impossible when createMiddleware is automating the piping.

**Comment by kevmoo** [comment]
That's good feedback! We should add those details to the createMiddleware
function.

Honestly, I don't find much use it in!

**Comment by AKushWarrior** [comment]
Yeah, the issue with it is that the primary purpose of middleware is to abstract away painful setup for inner Handlers, but that's much more difficult if you can't communicate with those Handlers. I do like the style a bit more though; with "function-style" middleware, you have to define 3 nested functions, which is doable but ugly.

I can't really think of a non-destructive way to make the method more useful. Maybe, if you want to edit the Request, you return a modified version of the request in the `requestHandler` callback:
```dart
createMiddleware(requestHandler: (request) {
   var newRequest = request.change(*/mutate request*/);
   return newRequest;
});
```
And if you want to pass on the Request you maintain the current behavior, which is returning null:
```dart
createMiddleware(requestHandler: (request) {
   // logging or something
   return null;
});
```
But that would hurt type safety, because requestHandler would need the type signature `dynamic Function(Request)` instead of `FutureOr<Response?> Function(Request)` (It can return either a Response, null, or Request in this case).

I think the best move is probably just adding a note to the documentation about manually defining middleware, like you suggested.
