### ISSUE TITLE
Using a non-existent route a 2nd time causes an error

### ISSUE THREAD

**Issue by xeu100** [dart-lang/shelf#197]
The error:
`Asynchronous error
Bad state: The 'read' method can only be called once on a shelf.Request/shelf.Response object.
package:shelf/shelf_io.dart 142:11  handleRequest`

Route not found is what you would expect, but after going to a non-existent route twice, this error appears. I'm using shelf_io and the shelf route generator.

**Comment by kevmoo** [comment]
I'd need to see more of your code to understand what's going on here.
