### ISSUE TITLE
How can I crate file upload api using shelf (form-data)

### ISSUE THREAD

**Issue by rajan995** [dart-lang/shelf#199]
I am stuck for create a file upload api please provide me any reference link . i was already spend 3 days for search regarding this issue please help 

thanks

**Comment by kevmoo** [comment]
You'll have to parse the form bits in the upload request and "do the right thing".

This package is meant to just support the basics. I did a quick search – it seems no one has implemented this yet!

**Comment by kevmoo** [comment]
Maybe this guy? https://pub.dev/packages/multipart
