### ISSUE TITLE
Shelf Header with latin caracter is giving error (Inspeção 69-ID-59. Até 07-09-2022.pdf)

### ISSUE THREAD

**Issue by gagregori** [dart-lang/shelf#201]
Error
 "FormatException: Invalid HTTP header field value: \"InspeÃ§Ã£o 69-ID-59. AtÃ© 07-09-2022.pdf\" (at character 6)\nInspeÃ§Ã£o 69-ID-59. AtÃ© 07-09-2022.pdf\n     ^\n"
 
 Code
 Future<shelf.Response> addAttachmentReference(shelf.Request request, String revisionID) async {  
         String? fileName = request.headers['filename'];
 }

**Comment by kevmoo** [comment]
Can you include the full stack trace? I wonder if this is coming from `dart:io` (the SDK) and not pkg:shelf

**Comment by gagregori** [comment]
I have no stack trace because It is a shelf request answer

2021-09-10T14:22:24.293295  0:00:00.048497 POST    [403] /api/vehicle/8187baef-8405-4d13-9cc6-27767daa67f5/attachment

{
    "error": "FormatException: Invalid HTTP header field value: \"InspeÃ§Ã£o 69-ID-59. AtÃ© 07-09-2022.pdf\" (at character 
    6)\nInspeÃ§Ã£o 69-ID-59. AtÃ© 07-09-2022.pdf\n     ^\n"
}

And the server LOG there is no error to copy paste here.

**Comment by gagregori** [comment]
what may help it is the header name in post: it is Inspeção 69-ID-59. Até 07-09-2022.pdf

**Comment by gagregori** [comment]
Thank you for answering me, but I have discovered by myself, Dart does not support latin caracteres in header, then I'm using the body.
