### ISSUE TITLE
Provide an ETag If-None-Match middleware for GET and HEAD requests

### ISSUE THREAD

**Issue by juancastillo0** [dart-lang/shelf#210]
Hi, thanks for your work!

I was wondering whether some [ETag](https://developer.mozilla.org/docs/Web/HTTP/Headers/ETag) and [If-None-Match](https://developer.mozilla.org/docs/Web/HTTP/Headers/If-None-Match) utilities for GET and HEAD requests belong in this package. From some of the issues, I can see that you want to keep shelf very lean, however maybe it makes sense for it to be one of the core utilities in shelf, maybe even enable the ETag computation and verification by default. Some servers like express-js enable it by default. Also, the [If-Modified-Since](https://developer.mozilla.org/docs/Web/HTTP/Headers/If-Modified-Since) header serves the same purpose in safe HTTP methods and there is some code ([`Request.ifModifiedSince`](https://github.com/dart-lang/shelf/blob/769c76abf5550d1a0441822f69e8382a62ca19f1/lib/src/request.dart#L74)) in shelf related to that.

Maybe a `Middleware` like the following, could be implemented:

```dart
import 'dart:convert' show Encoding;
import 'dart:io' show HttpHeaders;

import 'package:crypto/crypto.dart' show sha1;
import 'package:shelf/shelf.dart';

Middleware etag({
  Future<String> Function(Stream<List<int>>, Encoding?)? hasher,
}) {
  return (handler) {
    return (request) async {
      if (!['GET', 'HEAD'].contains(request.method)) {
        return handler(request);
      }
      final response = await handler(request);
      if (response.statusCode >= 300) {
        return response;
      }

      final ifNoneMatch = request.headersAll[HttpHeaders.ifNoneMatchHeader];
      final settedEtag = response.headers[HttpHeaders.etagHeader];
      if (settedEtag != null) {
        // ETag already set
        if (ifNoneMatch != null && ifNoneMatch.contains(settedEtag)) {
          // set ETag matches If-None-Match header
          return Response.notModified(
            headers: response.headersAll,
            context: response.context,
          );
        }
        return response;
      }

      // Copy the body since `response.read` returns a single
      // subscription stream, which can't be used in the response
      // because we are using it to calculate the ETag hash
      final bodyCopy = <List<int>>[];
      final bodyStream = response.read().map((buf) {
        bodyCopy.add(buf);
        return buf;
      });

      final String bodyHash;
      if (hasher != null) {
        bodyHash = await hasher(bodyStream, response.encoding);
      } else {
        final digest = await bodyStream.transform(sha1).single;
        // sha1 hash in HEX
        bodyHash = '"${digest.toString()}"';
      }

      if (ifNoneMatch != null && ifNoneMatch.contains(bodyHash)) {
        // computed ETag matches If-None-Match header
        return Response.notModified(
          headers: {...response.headersAll, HttpHeaders.etagHeader: bodyHash},
          context: response.context,
        );
      }

      // Return the response with the copied body and the computed ETag header
      return response.change(
        body: Stream.fromIterable(bodyCopy),
        headers: {HttpHeaders.etagHeader: bodyHash},
      );
    };
  };
}
```
It copies the body, maybe related [10](https://github.com/dart-lang/shelf/issues/10).

There is an [etag](https://pub.dev/packages/etag) package in pub.dev for computing the etag it's a port from https://github.com/jshttp/etag used in express-js. Also uses sha1, but encodes it in base64 and adds a length prefix `"${body.length}-<base64sha1>"` and uses the modified time for [FileStat](https://api.dart.dev/stable/2.14.4/dart-io/FileStat-class.html) similar to the usage of `Request.ifModifiedSince` in [shelf_static](https://github.com/dart-lang/shelf_static/blob/202ec1a53c9a830c17cf3b718d089cf7eba568ad/lib/src/static_handler.dart#L182).

**Comment by kevmoo** [comment]
This is a great idea, but something that we'd like want outside this package. We're trying to keep the bits here super simple!
