### ISSUE TITLE
Need a documentation’s  for Shelf. 

### ISSUE THREAD

**Issue by chetanxpatil** [dart-lang/shelf#214]
I have been working on flutter for 2 years now. I feel that dart should increase the scope for the webserver. Having one language to handle apps and web servers can be significant. Many people around me want to make a web server using dart but lack resources and documentation. People would love to have their hands on the shelf with good documentation. Having a good starter document will help evolve this because one needs to see errors to understand and make something. We need to try, but to try, we have nothing. Please help us out. Many people like me want to see a framework that uses dart as a backend server.

**Comment by santoshakil** [comment]
I also need this

**Comment by Shubhamjaitapkar** [comment]
yes, I am also looking for a backend framework or shelf documentation. Need it baddly.

**Comment by kevmoo** [comment]
Given what's in the README - https://github.com/dart-lang/shelf – what else do you want to know?

**Comment by chetanxpatil** [comment]
[](https://stackoverflow.com/questions/71258020/dart-package-cant-create-file-inside-docker)

**Comment by chetanxpatil** [comment]
https://stackoverflow.com/questions/71258020/dart-package-cant-create-file-inside-docker

**Comment by santoshakil** [comment]
> Given what's in the README - https://github.com/dart-lang/shelf – what else do you want to know?

Don't you think, this is not a brief documentation?
For example, hive documentation on pub.dev. See, how brief the hive documentation is. We want documentation of **shelf** like **hive**.

**Comment by chetanxpatil** [comment]
Exactly

**Comment by chetanxpatil** [comment]
There in no topic for static handlers and anything else.

**Comment by easazade** [comment]
usage of dart backend is increasing. shelf definitely needs a decent enough documentation
