### ISSUE TITLE
Middlewares have no support to change request object

### ISSUE THREAD

**Issue by busslina** [dart-lang/shelf#234]
I had to do my own handler implementation in order to be able to have a Pipeline of handlers (middlewares) which each one of them can change the request object then this new request is passed to the next handler in the pipeline.

For that goal, my handler returns a Wrapper object that can contain either a Request or a Response.

Its weird that Shelf miss this feature or maybe I am wrong, if anyone can explain how to do that I would appreciate. 

Thanks

**Comment by kevmoo** [comment]
Would you include some example code? You can absolutely change request/response in middleware. I'm not sure I follow your request!

**Comment by busslina** [comment]
The thing is that the middleware must return null or Response. If null, then inner handler is executed. You can modify a request by calling its method change(), that creates another request object. The thing is that you can't pass it to the next middleware/handler because you must return null for that. Next middleware/handler will receive always the first and unmodified request.

**Comment by kevmoo** [comment]
@busslina – put in your code. You may be confusing `Pipeline` with `Cascade` which do different things.

**Comment by busslina** [comment]
https://pub.dev/documentation/shelf/latest/shelf/Cascade-class.html

Thank you, didn't knew about Cascade. This resolve the problem.

Thank you

**Comment by busslina** [comment]
With pipeline I can't find a way to modify request.

```
void pipelineTest() async {
  final handler =
      Pipeline().addMiddleware(createMiddleware(requestHandler: (req) {
    print('Middleware 1');

    // You can clone & modify into a new request object
    // But yo can't pass it to NEXT.
    final newReq = req.change(context: {'foo': 'bar'});

    // Handling response
    // return Response.ok('');

    // Not handling response
    return null;
  })).addMiddleware(createMiddleware(requestHandler: (req) {
    print('Middleware 2');

    // This will print 'null'
    print(req.context['foo']);

    return null;
  })).addHandler(
    (req) {
      print('Handler');

      // This will print 'null'
      print(req.context['foo']);
      return Response.ok('Hello world');
    },
  );

  final server = await serve(handler, '127.0.0.1', 8080);
  print('Serving at http://localhost:8080');
}
```

**Comment by busslina** [comment]
Smae happens with Cascade

```
void cascadeTest() async {
  final handler = Cascade().add((req) {
    print('Handler 1');

    // You can clone & modify into a new request object
    // But yo can't pass it to NEXT.
    final newReq = req.change(context: {'foo': 'bar'});

    // Not handling
    return Response(404);
  }).add((req) {
    print('Handler 2');

    // This will print 'null'
    print(req.context['foo']);

    // Handling
    return Response.ok('Hello world');
  }).handler;

  final server = await serve(handler, '127.0.0.1', 8080);
  print('Serving at http://localhost:8080');
}
```

**Comment by kevmoo** [comment]
Oh! Don't use `createMiddleware` 😀 

https://github.com/kevmoo/knarly_vote/blob/main/shelf_jwt_auth/lib/shelf_jwt_auth.dart

You can create `Middleware` without `createMiddleware`

**Comment by busslina** [comment]
That was great. Thank you very much

**Comment by busslina** [comment]
SOLVED

```
void pipelineTestNew() async {
  final handler = Pipeline().addMiddleware((Handler innerHandler) {
    return (req) {
      print('Middleware');

      // Modifying request
      final newReq = req.change(context: {'foo': 'bar'});
      return innerHandler(newReq);
    };
  }).addHandler((req) {
    print('handler');

    // This will print 'null'
    print(req.context['foo']);
    return Response.ok('Hello world');
  });

  final server = await serve(handler, '127.0.0.1', 8080);
  print('Serving at http://localhost:8080');
}
```
