### ISSUE TITLE
Found 2 files excluded from sound null safety in pkgs/shelf/

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/shelf#238]
Found 2 files excluded from sound null safety in pkgs/shelf/:

```
pkgs/shelf/test/opt_out_io_test.dart:5:// @dart=2.9
pkgs/shelf/test/opt_out_test.dart:5:// @dart=2.9
```

See https://github.com/dart-lang/sdk/issues/49169 for more context.

**Comment by jakemac53** [comment]
These tests are specifically testing the opted out behavior, it looks like it does explicitly support passing null from opted out code where it wouldn't actually be allowed in opted in code, so maybe worth keeping.

**Comment by devoncarew** [comment]
I'm only trying to find unintentional opt-outs - null safety conversions that weren't quite finished.

If these are both intentional - testing the opt-out behavior - feel free to close this issue.
