### ISSUE TITLE
Listen on unix domain socket

### ISSUE THREAD

**Issue by kkazuo** [dart-lang/shelf#249]
Please consider listening capable on unix domain socket.
it's useful for Shelf by upstream of nginx reverse proxy.
I think that Dart SDK HttpServer can listen on unix domain socket already.

https://github.com/dart-lang/sdk/blob/e995cb5f7cd67d39c1ee4bdbe95c8241db36725f/tests/standalone/io/http_on_unix_socket_test.dart#L13

**Comment by kevmoo** [comment]
You can use `shelf` by providing an `HttpServer` to this function – https://pub.dev/documentation/shelf/latest/shelf_io/serveRequests.html

`HttpServer` implements `Stream<HttpRequest>` – try that!
