### ISSUE TITLE
[Bug] Reading body in middleware throws error

### ISSUE THREAD

**Issue by hnord-vdx** [dart-lang/shelf#256]
I get this error when trying to read the body in a middleware I created:

```
Asynchronous error
Bad state: The 'read' method can only be called once on a shelf.Request/shelf.Response object. 
package:shelf/shelf_io.dart 143  handleRequest
```

The middleware code snippet:
```dart
return createMiddleware(
      requestHandler: (req) {

       // do something with request

      responseHandler: (resp) async {
    
        final body = await resp.readAsString(); //! throws error
        if (body.isEmpty) {
          return resp;
        }

       // do something with body

        return null;
      },
 );
```

**Comment by kevmoo** [comment]
Yup. If you want to read the body in middleware, you have to create a new response object w/ a copy of the data.

This is the *ONLY* way to handle streaming output where the emitter is only accessing the data once – like reading a file.

**Comment by hnord-vdx** [comment]
Ah sorry! Yes, makes sense. Thank you

**Comment by hnord-vdx** [comment]
How exactly is a copy created? I tried using .change() but I get the same error

**Comment by kevmoo** [comment]
You need to re-populate the body with the read content.
