### ISSUE TITLE
Send Message To all connected devices

### ISSUE THREAD

**Issue by MahmoudArabyDev** [dart-lang/shelf#260]
I have shelf socket server installed on application and multiple appications are connected to that shelf server .

now i need to reroute any message i recieve from any device to all devices .

Shelf Socket Server
192.168.0.123
Connected Devices
192.168.0.120
192.168.0.121
192.168.0.122

if i recieved a message from 192.168.0.120 i want it to be repeated to all other devices ...
[ 192.168.0.120 , 192.168.0.121 , 192.168.0.122 ]is that possible to do on shelf .

**Comment by kevmoo** [comment]
Read through the API documentation for Shelf. It's pretty small. You likely need to investigate WebSockets or similar for what you're trying to do.
