### ISSUE TITLE
Optional trailing slash 

### ISSUE THREAD

**Issue by jaumard** [dart-lang/shelf#264]
Hello,

I'm having trouble to support that `/api/v1/users` and `/api/v1/users/` works by sending the same things.

```
class Server {
  @Route.mount('/api/v1/')
  Router get _api => ApiV1().router;

  Router get router => _$ServerRouter(this);
}

class ApiV1 {
  @Route.mount('/users/')
  Router get _api => UsersService().router;

  Router get router => _$ApiV1Router(this);
}
class UsersService {
  UsersService();

  @Route.get('/')
  Future<Response> list(Request request) async {
    return Response.ok('["user1"]');
  }

  @Route.get('/<userId>')
  Future<Response> fetch(Request request, String userId) async {
    return Response.notFound('no such user');
  }

  Router get router => _$UsersServiceRouter(this);
}

```

With this only `/api/v1/users/` will work and the other will return 404, which is annoying. Is there any configuration to support this use case? Or anyway I could to support it currently? Thanks

**Comment by kevmoo** [comment]
Thoughts @jonasfj ?

**Comment by jonasfj** [comment]
@jaumard, I think it's covered here:
https://github.com/dart-lang/shelf/blob/master/pkgs/shelf_router/test/router_test.dart#L151-L179

try:
```dart
class ApiV1 {
  @Route.mount('/users/')
  Router get _api => UsersService().router;

  Router get router => _$ApiV1Router(this);
}
```

Feel free to make a PR improving documentation if this works.

**Comment by jaumard** [comment]
Hey @jonasfj thanks for the information, it works when you don't use mount indeed as I was using this previously. But my API will be big so I want to separate using mount, and with mount it doesn't work. 

It give me: 

```
[SEVERE] shelf_router_generator:shelf_router on lib/src/api_v1.dart:

The prefix "/users" in shelf_router.Route.mount(prefix) annotation must begin and end with a slash
package:dashboard_server/src/api_v1.dart:9:14
```

Maybe it's supported by the router but not yet allowed by the generator?

**Comment by jaumard** [comment]
Look like it's what's mention on that issue too https://github.com/dart-lang/shelf/issues/244

**Comment by jonasfj** [comment]
Yes, closing in favor of https://github.com/dart-lang/shelf/issues/244.
