### ISSUE TITLE
DartDocs for `Pipeline` is broken.

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/shelf#271]
From `Pipeline` class:

```dart
/// Note: this package also provides `addMiddleware` and `addHandler` extensions
//  members on [Middleware], which may be easier to use.
class Pipeline {

```

Notice the final line in the docs starts with `//`, not `///`. So it doesn't show up in the docs.

**Comment by devoncarew** [comment]
Good catch! Interested in sending a PR for it?

**Comment by renatoathaydes** [comment]
I will do that in exchange for you guys also letting me fix https://github.com/dart-lang/shelf/issues/270.

Deal?

**Comment by devoncarew** [comment]
Fixing #270 seems reasonable; @kevmoo and @natebosch would be good reviewers for any PR for that. If the fix will be non-trival, you might want to discuss the solution in that issue, just so you can know ahead of time whether it's something we think we can accept.
