### ISSUE TITLE
Question: How performant is shelf?

### ISSUE THREAD

**Issue by vanlooverenkoen** [dart-lang/shelf#287]
We are looking for a way to implement our new API. 

We are building a quite simple application. (think cms, event tool, time tracking,...)

I am not sure what the performance of shelf will be. Are there some resources available on that?

What type of hardware should be used? 

Is shelf a good fit for an API that will need to handle peak traffic? (20k users at 18:00 for only 30 min)

**Comment by kevmoo** [comment]
My answer: fast enough for pub.dev

`shelf` does add some overhead on top of `dart:io` `HttpServer` but this is to enable a cleaner development model that hopefully means you have more correct code.

If you plan to deploy `shelf`, I'd recommend testing it with your target hardware. 

Look at a tool like https://github.com/wg/wrk to test a server.

**Comment by vanlooverenkoen** [comment]
Alright thanks!

pub.dev itself is fully written in shelf?
Are there any other example of big websites that are using shelf?

**Comment by kevmoo** [comment]
https://github.com/dart-lang/dart-pad

dartpad.dev :-)
