### ISSUE TITLE
Flutter static dir no sach file or directory 

### ISSUE THREAD

**Issue by getdbjs** [dart-lang/shelf#306]
Which path should be entered for the static files placed in the assets folder? If you create a folder in the project root, it does not exist for Android and iOS. I need to serve an angular app in the webview from localhost. Where should the web files be placed and how should the static folder be configured?

**Comment by kevmoo** [comment]
I'm not sure. I don't know what files get shared within a native application. Once you figure that out, it should be easy – but this is not an issue specific to `shelf_static`
