### ISSUE TITLE
Android root directory not accessible

### ISSUE THREAD

**Issue by lokeb** [dart-lang/shelf#311]
Hi. I am able to use this with Flutter when run on Linux, but it can't find the root directory when run on Android.
```
final _staticHandler = shelf_static.createStaticHandler('webserver',
    defaultDocument: 'index.html');
```

The Assets are available in `pubspec.yaml`:

```
assets:
  - webserver/
```

The static content is under `webserver`. What could be the reason?

**Comment by kevmoo** [comment]
Shelf isn't anything special here. I'd research how one accesses files in general on Android. There's nothing special about `shelf_static`
