### ISSUE TITLE
HTTP to HTTPS redirect

### ISSUE THREAD

**Issue by gaddlord** [dart-lang/shelf#312]
Please advice on weather redirecting HTTP requests to HTTPS is possible with Router().

**Comment by kevmoo** [comment]
I don't think you can route on HTTP vs HTTPs. It'd be easy https://pub.dev/documentation/shelf/latest/shelf/Middleware.html to write to handle it, though!

**Comment by gaddlord** [comment]
Indeed that resolved it. I implemented:

`final _redirectToHttps = createMiddleware(
  requestHandler: (final Request request) {
    if (request.requestedUri.scheme == 'http') {
      final location =
          request.requestedUri.replace(scheme: 'https').toString();
      return Response.movedPermanently(location);
    }
    return null;
  },
);`

and called as:
`final server = await serve(
      const Pipeline()
        .addMiddleware(_redirectToHttps)
        .addHandler(
          Cascade()
              .add(staticFileHandler)
              .add(router)
              .add(_notFoundHandler)
              .handler,
        ),
      ip,
      port,
      securityContext: Configuration.useHttps ? _getSecurityContext() : null,
    );`

**Comment by kevmoo** [comment]
Great @gaddlord – even tighter

```dart

Handler _redirectBetter(Handler innerHandler) => (request) {
      if (request.requestedUri.scheme == 'http') {
        final location =
            request.requestedUri.replace(scheme: 'https').toString();

        return Response.movedPermanently(location);
      }

      return innerHandler(request);
    };
```

**Comment by gaddlord** [comment]
Seems like not possible to simultaneously have bind() and bindSecure() due to the implementation

```
Future<HttpServer> serve(
  Handler handler,
  Object address,
  int port, {
  SecurityContext? securityContext,
  int? backlog,
  bool shared = false,
  String? poweredByHeader = 'Dart with package:shelf',
}) async {
  backlog ??= 0;
  var server = await (securityContext == null
      ? HttpServer.bind(address, port, backlog: backlog, shared: shared)
      : HttpServer.bindSecure(
          address,
          port,
          securityContext,
          backlog: backlog,
          shared: shared,
        ));
  serveRequests(server, handler, poweredByHeader: poweredByHeader);
  return server;
}
```
Seems like my code runs either as HTTP or HTTPS. But I cannot make them run simultaneously. Please advice.

**Comment by kevmoo** [comment]
https://pub.dev/packages/http_multi_server ?

**Comment by gaddlord** [comment]
Decided to workaround it having 80 and 443 NAT to 3030.
```
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 3030
sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 3030
```
I run the Dart server on 3030 and have the OS redirect 80 (HTTP) and 443(HTTPS) to 3030.

That seems to be working. Thank you @kevmoo !
