### ISSUE TITLE
Add swagger documentation

### ISSUE THREAD

**Issue by rafaelovandov** [dart-lang/shelf#325]
Generate swagger documentation based on models, endpoints and etc.
link: https://swagger.io/

**Comment by kevmoo** [comment]
I think folks have already run on that - https://pub.dev/packages/openapi_generator

We're keeping the bits here pretty simple.

**Comment by clragon** [comment]
the library you linked does the opposite; it generates clients based on swagger documentation, not swagger documentation based on clients. 

there doesnt seem to be any way of generating swagger docs from shelf clients from what I have seen.
Though I understand that its not the responsibility of the shelf package to provide this functionality either.
