### ISSUE TITLE
Add Problem Details

### ISSUE THREAD

**Issue by bytes7bytes7** [dart-lang/shelf#327]
It would be great to add [Problem Details](https://www.rfc-editor.org/rfc/rfc7807) and new ContentType "application/problem+json" as an extension to ContentType from dart:io
```
HTTP/1.1 403 Forbidden
Content-Type: application/problem+json
Content-Language: en

{
  "type": "https://example.com/probs/out-of-credit",
  "title": "You do not have enough credit.",
  "detail": "Your current balance is 30, but that costs 50.",
  "instance": "/account/12345/msgs/abc",
  "balance": 30,
  "accounts": ["/account/12345",
      "/account/67890"]
}
```

**Comment by kevmoo** [comment]
This is a great idea, but likely something that would be best as a supplementary package and not baked into shelf itself.

Did you have a specific part you wanted to extend w/ this logic?

**Comment by bytes7bytes7** [comment]
> This is a great idea, but likely something that would be best as a supplementary package and not baked into shelf itself.
> 
> Did you have a specific part you wanted to extend w/ this logic?

Excuse me, I don't fully understand you. What do you mean here "Did you have a specific part you wanted to extend w/ this logic?"

**Comment by kevmoo** [comment]
@bytes7bytes7 – please explain exactly what you want added. It's not clear how you want the behavior of things to change.

**Comment by bytes7bytes7** [comment]
I will open a PR
