### ISSUE TITLE
Move package:shelf_router and package:shelf_router_generator to the tools.dart.dev publisher

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/shelf#348]
Most of the shelf packages in this repo are published by the `tools.dart.dev` publisher; `package:shelf_router` and `package:shelf_router_generator` are the only exceptions (both published through `labs.dart.dev`). I believe both are in use by the pub client however, seem to be maintained, and are likely fairly mature - not requiring much continued investment?

@jonasfj - what do you think about moving these to the tools publisher?

cc @kevmoo @mit-mit

**Comment by jonasfj** [comment]
They are used on the pub.dev server.. IMO, doesn't matter, but yes, they
are not really experiments anymore :)

**Comment by devoncarew** [comment]
Done (https://pub.dev/packages/shelf_router, https://pub.dev/packages/shelf_router_generator).
