### ISSUE TITLE
How to ignore the request that find the file with success.

### ISSUE THREAD

**Issue by SittiphanSittisak** [dart-lang/shelf#359]
I am using `shelf_router` to manage the API route. I have a path to receive every request that my API path doesn't contains it. 
```
final router = shelf_router.Router()
....
..all('/<ignored|.*>', (Request request) async {
    ....
  });
```
And I have recorded this in my log file.

However, I am using `shelf_static` to manage the file path.
```
final staticHandler = shelf_static.createStaticHandler('folder');
```
and I am using it like this below.
```
final cascade = Cascade().add(_staticHandler).add(_router);
```

The problem is when the client tries to show a file from my API, the `/<ignored|.*>` will run too and it will record this in the log file.
My log file contains the note about this too much.
How I prevent this when the request about finding a file and found this file?
(or should I extract the path from the request and try to check that the file exists before recording it or this package already has a solution?)

**Comment by gusrylmubarok** [comment]
To prevent the `/<ignored|.*>` route from being triggered when the client tries to access a file managed by `shelf_static`, you can modify your code as follows:
```
final router = shelf_router.Router();
// ...
router.all('/<ignored|.*>', (Request request) async {
  // Check if the request path matches a file in the 'folder'
  var fileHandler = shelf_static.createStaticHandler('folder');
  if (await fileHandler(request) != null) {
    // The request matches a file, so don't record it in the log
    return Response.notFound('');
  } else {
    // The request doesn't match a file, record it in the log
    // Your logging logic here
  }
});

final cascade = Cascade().add(staticHandler).add(router);
```

In this updated code, before recording the request in the log, you first check if the request path matches a file in the specified `'folder'` using the `shelf_static.createStaticHandler` middleware. If the request matches a file, you can return a `Response.notFound('')` to indicate that the file should be served by `shelf_static `and should not be recorded in the log.

By doing this, requests for files managed by `shelf_static` will be handled separately and won't trigger the logging logic in your `/<ignored|.*>` route.

**Comment by SittiphanSittisak** [comment]
Your solution does not work for me and my lints always warn that `await fileHandler(request) != null` always be true.
I notice the request to get an existing image file, the URL always be `favicon.ico`.
So I fix it by using this below at the top of my function.
```
if (request.url.path == 'favicon.ico') return Response.ok(null);
```

**Comment by SittiphanSittisak** [comment]
@gusrylmubarok   Thank you for the example. But your solution does not work for me and my lints always warn that `await fileHandler(request) != null` always be true.
I notice the request to get an existing image file, the URL always be `favicon.ico`.
So I fix it by using this below at the top of my function.
```
if (request.url.path == 'favicon.ico') return Response.ok(null);
```
