### ISSUE TITLE
Invalid argument (requestedUri): handlerPath "/" and url "43" must combine to equal requestedUri path "443".: Instance of '_SimpleUri'

### ISSUE THREAD

**Issue by dumabg** [dart-lang/shelf#369]
I try to create a server proxy. I configured my Firefox browser proxy. All the url petitions gives the error:

Invalid argument (requestedUri): handlerPath "/" and url "43" must combine to equal requestedUri path "443".: Instance of '_SimpleUri'

The code used for creating the proxy server is the code that you suggest in the "How to build a proxy server with shelf?" issue.

**Comment by ryanaston** [comment]
I am seeing this same error occasionally in my shelf logs, and I am not using shelf_proxy.  Unsure when it began nor how to trigger consistently.

**Comment by aler** [comment]
see same error logs
```
Error parsing request.
Invalid argument (requestedUri): handlerPath "/" and url "43" must combine to equal requestedUri path "443".: Instance of '_SimpleUri'
dart:isolate  _RawReceivePort._handleMessage
```

**Comment by kevmoo** [comment]
Help? Any example requests? Code samples?

**Comment by ThatNerdSquared** [comment]
It's reproducible with the [`shelf_proxy` example](https://pub.dev/packages/shelf_proxy):
```
import 'package:shelf/shelf_io.dart' as shelf_io;
import 'package:shelf_proxy/shelf_proxy.dart';

void main() async {
  var server = await shelf_io.serve(
    proxyHandler("https://dart.dev"),
    'localhost',
    8080,
  );

  print('Proxying at http://${server.address.host}:${server.port}');
}
```

I spent some time looking through shelf the other day as I ran into this error with a project I was working on. After some investigation, I concluded that **sending HTTPS traffic through the server without a `SecurityContext` was the cause** of the problem.

**Comment by Tienisto** [comment]
I get the same error but occasionally also with port 80:

```text
Error parsing request.
Invalid argument (requestedUri): handlerPath "/" and url "0" must combine to equal requestedUri path "80".: Instance of '_SimpleUri'
dart:isolate  _RawReceivePort._handleMessage
```

This happens alongside with the 443 errors. It is important to note, that I cannot reproduce it myself. I assume that a malious attacker makes some weird requests.

**Comment by ThatNerdSquared** [comment]
Is anybody else able to repro with my [above example](https://github.com/dart-lang/shelf/issues/369#issuecomment-1710999378)?
1) `dart create` a new project, add shelf, copy the example into `bin/[projectname].dart`
2) `dart run`
3) set your system HTTP and HTTPS proxy to `localhost 8080`
4) attempt to access any HTTPS website from a browser

As for what could be done - if it's just a missing `securityContext` argument, it's not really a bug, but possibly something could be added to the exception to hint at a missing `securityContext`?

**Comment by Tienisto** [comment]
Do you know how we can supress this error message? I put a try catch in every possible way but this error keeps spamming my logs.

**Comment by yixiaco** [comment]
I analyzed the source code and found that it was caused by this:
<img width="812" alt="image" src="https://github.com/dart-lang/shelf/assets/30982989/afa4acfc-27ea-4c3f-9e89-0829b97b29bc">

https://github.com/dart-lang/shelf/assets/30982989/f8b74e79-5a62-44b1-91cc-347b20c1a8dd




> 恶意行为者发送“奇怪”的输入很有可能会导致异常——与 URI 解析有关。这比未定义的行为要好得多！
> 
> 除非我们能得到可靠的复制品，否则就将其结束。不确定我们会如何处理这个错误。
