### ISSUE TITLE
Add support for multi-valued headers.

### ISSUE THREAD

**Issue by nex3** [dart-lang/shelf#44]
Some solution is needed for headers that have multiple values. Most headers can be losslessly merged together or split apart, and Shelf should help with the splitting when users want to access them as multiple values; some cookie-related headers can't be losslessly combined, and can only be accessed through multi-headers.

Something as simple as `Map<String, List<String>> get Message.multiHeaders` is probably enough here. It could even lazily parse the values from the underlying data.

**Comment by isoos** [comment]
What's the preferred way of setting/defining multiple headers (and overriding them in `Response.change`)? (It seems to be a bit more complex than the `multiHeaders` getter.)

**Comment by kevmoo** [comment]
🤷 – I don't think anyone is going to give you a good answer here.
