### ISSUE TITLE
How to publish/deploy shelf backend app

### ISSUE THREAD

**Issue by MalikSamiAwan** [dart-lang/shelf#446]
I have developed a backend app in flutter shelf that basically handles files uploading and database cruds i have developed **wallpaper app** in flutter both front-end and backend 
now currently i am running it localhost port 8080 and using xamp for db cruds and its working fine 
**But i don't know how can i publish it to any server**

in my use case i am looking for server that has flexible capacity for storage like 10-100gb 

can please somebody help me in this

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/samples/tree/main/server/simple
