### ISSUE TITLE
Middleware can't both read request body and hijack in same pipeline

### ISSUE THREAD

**Issue by emilniklas** [dart-lang/shelf#46]
If a pipeline contains a middleware that reads the request body, it must pass on a new Request. We can't use Message.change because that will attempt to read the body again (StateError), so we must do something like this:
```dart
new Request(
  request.method,
  request.url,
  body: '');
``` 
However now this new request cannot be hijacked, and we can't do this:
```dart
new Request(
  request.method,
  request.url,
  body: '',
  onHijack: request.onHijack);
```
because `onHijack` is private (`_onHijack`).

This should really be possible, since we just want to extract the request body, read it *once*, and pass on the request, allowing it to later be hijacked as usual.

**Comment by emilniklas** [comment]
Can I pass on the hijack call? Something like `new Request(m, u, onHijack: (c) => request.hijack(c));`?

**Comment by nex3** [comment]
It doesn't make sense to read the body and also hijack the request. Hijacking is taking control of the request's underlying stream and sink; reading the body involves closing them. They're fundamentally incompatible operations.

**Comment by emilniklas** [comment]
The hijacking is in another middleware, based on other other parameters than considers this middleware. Specifically, this is what happens:

Middleware A) reads the body of the request and parses it into an Input object, putting it into the context.
Middleware B) checks if the request is a websocket upgrade request, in which case it hijacks the request. 

For architectural reasons I wanted to avoid changing the order of these, but I figure it's illogical to parse body before checking upgrade, so I'll probably swap it anyway.

**Comment by nex3** [comment]
It doesn't matter how separate the middleware is; under the covers, there's only one request, and that request's state is unavoidably changed when it's read in a way that makes hijacking impossible.

**Comment by emilniklas** [comment]
Okay, I see now. Thanks for your time!
