### ISSUE TITLE
Improve error for handlers that fail to return a Response

### ISSUE THREAD

**Issue by davenotik** [dart-lang/shelf#51]
In refactoring a bunch of code to use Shelf, I'm having to go through all my handlers to make sure each returns a `shelf.Response`. When a handler doesn't, I get an error like so:

```
ERROR - 2015-10-26 21:43:14.523
Error thrown by handler.
The null object does not have a getter 'statusCode'.

NoSuchMethodError: method not found: 'statusCode'
Receiver: null
Arguments: []
dart:isolate  _RawReceivePortImpl._handleMessage
```

Surely this can be more graceful than erroring on `statusCode` somewhere deep in Shelf code? I get now that this means a handler wasn't returning a `Response` as it is expected to, but I still have trouble locating which request this was for. Perhaps the error can alert me of the corresponding request?

**Comment by nex3** [comment]
The error you're seeing isn't something the adapter can detect—it's caused by some middleware that expects a non-`null` response value. The adapter can be better about providing request context for errors, though.
