### ISSUE TITLE
Is there any way in shelf to return a streamed response ?

### ISSUE THREAD

**Issue by Pacane** [dart-lang/shelf#54]
With `dart:io` I can do the following

```dart
await for (HttpRequest request in requestServer) {
  Stream<int> counterStream =
      timedCounter(const Duration(seconds: 1), 15).map((int x) => x * 2);
  request.response.bufferOutput = false;
  counterStream.listen((int data) => request.response.writeln(data),
      onDone: () => request.response.close());
}
```
I was wondering if there was a way in shelf to:
A) Access a request's response, and write stuff to it via a stream.listen()
B) Set the response's bufferOutput to false

**Comment by kevmoo** [comment]
@Pacane here's a bit of an example of using a streamed body – https://github.com/dart-lang/shelf/blob/master/test/message_test.dart#L81

Basically: you can return a response *now* with a Stream for the body, but take your time to add data to the stream and close it – just make sure you close it. :smile:

**Comment by Andersmholmgren** [comment]
hmmm we did manage to get it working in the end via the `shelf.io.buffer_output` context param

```
return new Response.ok(counterStream, context: {"shelf.io.buffer_output": false});
```

Strangely, I'm not seeing that context param referenced in the test you linked so I rather confused how it is working

**Comment by kevmoo** [comment]
@anders-sandholm It's two bits

1) Provide stream content for the Response body (the example I provided)
2) Make sure dart:io doing the right thing

Looks like you figured out \#2

**Comment by kevmoo** [comment]
@anders-sandholm My sample was reading from the Response object directly, not from `dart:io`.
