### ISSUE TITLE
Move http message to its own package

### ISSUE THREAD

**Issue by adaojunior** [dart-lang/shelf#58]
Hi, I'm not really sure if this makes sense for dart, but I come from PHP and in PHP we have a organization called PHP FIG and one of their goals is to create and maintain standards. One of their "recommendations" is [php-fig/http-message](https://github.com/php-fig/http-message) see also [PSR-7: HTTP message interfaces](http://www.php-fig.org/psr/psr-7/) and I notice SHELF has something very similar with Request, Response, Message, Body and I wonder if it makes sense to move some of this stuff to its own package so others may rely on an interface.

**Comment by nex3** [comment]
We've talked about this before, usually in the context of sharing interfaces with the `http` package. I think the API needs of code consuming requests is different enough than the needs of code producing them that this won't provide that much benefit, but I won't write it off until I finish my planned refactor of `http`.

**Comment by kevmoo** [comment]
Not planned.
