### ISSUE TITLE
Continuous streaming response for EventSource server

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/shelf#65]
I'm trying to implement a shelf handler for EventSource (or Server-Side Events), however I have two things missing:

- How can I know from a `shelf.Request` when it was closed by the client?
- How can I keep the connection open and continuously send messages into the response?

For this second one, is it enough to create a `shelf.Response` like this:
```dart
StreamController<List<int>> bodyStream = new StreamController<List<int>>();
shelf.Response response = new shelf.Response.ok(bodyStream, headers: responseHeaders);
```
And then keep adding messages into the `StreamController`?

**Comment by stevenroose** [comment]
I ended up using the hijacking feature and it worked like a charm!

https://github.com/stevenroose/dart-shelf_eventsource/blob/master/lib/shelf_eventsource.dart#L34

**Comment by shtse8** [comment]
> I ended up using the hijacking feature and it worked like a charm!
> 
> https://github.com/stevenroose/dart-shelf_eventsource/blob/master/lib/shelf_eventsource.dart#L34

you made an amazing package.
could you update this package to support the latest dart?
