### ISSUE TITLE
change() should remove nulled-out headers

### ISSUE THREAD

**Issue by nex3** [dart-lang/shelf#68]
If the headers map passed to `Message.change()` includes headers with `null` values, those headers should be removed from the map entirely. This is currently the effective behavior at least for `shelf_io`, which won't emit null-valued headers. However, currently `headers.containsKey()` can return false positives.

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/shelf/commit/978cb521881d252dc585601fbb814d696a1d30a5
