### ISSUE TITLE
Please bump version to 1.0 when stable

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/shelf#72]
Pre-1.0 version numbers make it look like the package is not yet ready for use.

**Comment by kevmoo** [comment]
I think we're pretty stable here. Not a bad idea...

@nex3 ?

**Comment by nex3** [comment]
I wouldn't want to do this without first getting the API to a place where I believe it thoroughly handles all common use-cases. Right now it's lacking support for multi-valued headers and specifically for cookies. If we can allocate some time to work on that, I think we could get this to 1.0.0 in short order.

**Comment by natebosch** [comment]
Closing since the null safety release will be published as `1.0.0-nullsafety` and then later as `1.0.0`. If we need breaking changes to improve use for cookies and multi headers we'll look at a  bump to `2.0.0` at that point.
