### ISSUE TITLE
Error parsing request if requestedUri.path contains ":"

### ISSUE THREAD

**Issue by zengyun261** [dart-lang/shelf#86]

**Comment by zoechi** [comment]
`:` is a reserved character https://tools.ietf.org/html/rfc3986#section-2.2
It needs to be percent-encoded https://tools.ietf.org/html/rfc3986#section-2.1

**Comment by kevmoo** [comment]
@zoechi – we think this is by-design?

**Comment by zoechi** [comment]
@kevmoo I think so. `:` doesn't seem to be a valid character in the path.
