### ISSUE TITLE
is there a way for shelf to share the connections among isolates ?

### ISSUE THREAD

**Issue by sandrobilbeisi** [dart-lang/shelf#88]
I use HttpServer.bind directly with shared: true on a system with up to four isolates
and I use the chief isolate as a data mothership

is it possible to do this whilst using shelf ?

**Comment by sandrobilbeisi** [comment]
it looks to me that shelf_io.dart doesn't have the 'shared' parameter ( not even for passthrough)
https://github.com/dart-lang/shelf/blob/master/lib/shelf_io.dart

I will attempt a monkey patch and communicate my findings

**Comment by sandrobilbeisi** [comment]
hmmm ... I just noticed that issue #56 references an attempted patch at
https://github.com/dart-lang/shelf/pull/56/commits/f51aebb343412b6e6011b039d16a1ffb303b3aeb

**Comment by kevmoo** [comment]
Or just use `serveRequests`. `HttpServer` is `Stream<HttpRequest> requests` – so follow your tricks to spin up a multi-isolate `HttpServer` – then pass it in there...

**Comment by sandrobilbeisi** [comment]
that's awesome ! thanks @kevmoo 

you forced me to read the comments and the code more thoroughly !

I'm trying it now and it seems to work ,...
 I'll post a skeleton example

**Comment by kevmoo** [comment]
🤘

From mobile. Sorry for brevity and/or spelling.

**Comment by KOGI** [comment]
@sandrobilbeisi did you ever get a skeleton example put together for this? It would be supremely helpful for me!

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/isolate/blob/master/example/http_server.dart

you can adapt this on top of shelf

**Comment by KOGI** [comment]
Thank you!
