### ISSUE TITLE
Long request cancel

### ISSUE THREAD

**Issue by ariesomers** [dart-lang/shelf#98]
When client make a request, which returns huge amount of data (for exapmle, large file), and client cancels request, what happens with shelf? 
Will data be fully written to response anyway? Or everything will fall?

**Comment by nex3** [comment]
Assuming that by "canceling the request", you mean "canceling the `StreamSubscription` to `Request.read()`", that cancellation will be forwarded to the underlying server. The specific behavior then is up to the underlying server implementation. I believe `dart:io` will close the socket that's handling the request and your machine won't receive any more data, but I'm not certain about that.
